name: Build and deploy ASP.Net Core app to Azure Web App - hporvenirapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301'
          include-prerelease: true

      # Fix for missing ICU package
      - name: Install ICU package
        run: sudo apt-get update && sudo apt-get install -y libicu-dev
      - name: Install ssl
        run: sudo apt-get install -y libssl1.1

      - name: Build with dotnet
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true # Set invariant globalization mode
        run: dotnet build HPorvenir.Web.Api/HPorvenir.Web.Api.csproj --configuration Release -v n

      - name: dotnet publish
        env:
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: true
        run: dotnet publish HPorvenir.Web.Api/HPorvenir.Web.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp -v n

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hporvenirappv2'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B854768443164600B56215BD52597AC0 }}
          package: .
